export { Cake } from "./Cake";
export { CakeBase } from "./CakeBase";
export { CreamLayer } from "./CreamLayer";
export { Topping } from "./Topping";
export { Candles } from "./Candles";
export { Candle } from "./Candle";
export { CakeExample } from "./CakeExample";
export { CAKE_THEMES, resolveCakeTheme } from "./themes";
export { CANDLE_COLOR_HEX, normalizeCandleColor } from "./candleColors";
export { apiCandlesToCandleColors, apiFlavorToCakeFlavor } from "./apiAdapter";
export type { CakeFlavor, CakeProps, CakeTheme, CakeThemeOverride, CandleColor } from "./types";
